name: Actions Worlflow
on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: D.suke

      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
